export declare const APP_NAME = "Eat & Meet";
export declare const APP_VERSION = "1.0.0";
export declare const APP_DESCRIPTION = "Premium Restaurant Management & POS System";
export declare const API_BASE_URL: string;
export declare const API_TIMEOUT = 30000;
export declare const API_VERSION = "v1";
export declare const JWT_ACCESS_EXPIRY = "15m";
export declare const JWT_REFRESH_EXPIRY = "7d";
export declare const BCRYPT_ROUNDS = 12;
export declare const MAX_LOGIN_ATTEMPTS = 5;
export declare const LOCKOUT_DURATION: number;
export declare const DEFAULT_PAGE_SIZE = 20;
export declare const MAX_PAGE_SIZE = 100;
export declare const THERMAL_PRINTER_WIDTH = 80;
export declare const RECEIPT_MAX_CHARS = 48;
export declare const KOT_MAX_CHARS = 48;
export declare const DEFAULT_TAX_RATE = 0.1;
export declare const DEFAULT_SERVICE_CHARGE = 0;
export declare const CURRENCY_SYMBOL = "\u00A3";
export declare const CURRENCY_CODE = "GBP";
export declare const CACHE_TTL: {
    MENU: number;
    CATEGORIES: number;
    TABLES: number;
    ORDERS: number;
    REPORTS: number;
    USER: number;
};
export declare const WS_EVENTS: {
    ORDER_CREATED: string;
    ORDER_UPDATED: string;
    ORDER_STATUS_CHANGED: string;
    KOT_CREATED: string;
    KOT_STATUS_CHANGED: string;
    TABLE_STATUS_CHANGED: string;
    INVENTORY_LOW_STOCK: string;
    DAY_CLOSED: string;
};
export declare const PERMISSIONS: {
    ORDER_CREATE: string;
    ORDER_READ: string;
    ORDER_UPDATE: string;
    ORDER_CANCEL: string;
    ORDER_REFUND: string;
    MENU_READ: string;
    MENU_CREATE: string;
    MENU_UPDATE: string;
    MENU_DELETE: string;
    INVENTORY_READ: string;
    INVENTORY_CREATE: string;
    INVENTORY_UPDATE: string;
    INVENTORY_ISSUE: string;
    INVENTORY_APPROVE: string;
    REPORTS_VIEW: string;
    REPORTS_EXPORT: string;
    STAFF_READ: string;
    STAFF_CREATE: string;
    STAFF_UPDATE: string;
    STAFF_DELETE: string;
    DISCOUNT_APPLY: string;
    DISCOUNT_MANAGE: string;
    DISCOUNT_APPROVE: string;
    DAY_CLOSE: string;
    DAY_CLOSE_APPROVE: string;
    EXPENSE_READ: string;
    EXPENSE_CREATE: string;
    EXPENSE_UPDATE: string;
    EXPENSE_DELETE: string;
    SETTINGS_READ: string;
    SETTINGS_UPDATE: string;
};
export declare const ROLE_PERMISSIONS: Record<string, string[]>;
//# sourceMappingURL=index.d.ts.map